version: '3.9'

services:
  revanced:
    build:
      context: .
      dockerfile: Dockerfile
    image: revanced-builder
    container_name: revanced-builder
    volumes:
      - .:/app:z
    command: /entrypoint
