name: Build Revanced APK

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-apk:
    name: APK Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Build APK
        run: |
          docker-compose up

      - name: Upload Build Artifact(youtube)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "apks/output.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: Latest
